import { useState } from 'react'
import {
  RadarChart,
  Radar,
  PolarGrid,
  PolarAngleAxis,
  PolarRadiusAxis,
  ResponsiveContainer,
} from 'recharts'
import {
  CheckCircle,
  XCircle,
  Link as LinkIcon,
  Loader2,
  AlertTriangle,
  Shield,
  FileText,
  Download,
} from 'lucide-react'

const INDICATOR_LABELS = {
  data_collection_disclosure: 'Data Collection Disclosure',
  data_use_purpose_specification: 'Data Use Purpose Specification',
  third_party_sharing_disclosure: 'Third-Party Sharing Disclosure',
  parental_consent_mechanism: 'Parental Consent Mechanism',
  coppa_ferpa_compliance_mention: 'COPPA/FERPA Compliance Mention',
  data_retention_policy: 'Data Retention Policy',
  user_data_rights: 'User Data Rights',
  data_security_encryption: 'Data Security & Encryption',
  tracking_technologies_disclosure: 'Tracking Technologies Disclosure',
}

const RADAR_SHORT = {
  data_collection_disclosure: 'Collection',
  data_use_purpose_specification: 'Purpose',
  third_party_sharing_disclosure: '3rd Party',
  parental_consent_mechanism: 'Consent',
  coppa_ferpa_compliance_mention: 'COPPA/FERPA',
  data_retention_policy: 'Retention',
  user_data_rights: 'User Rights',
  data_security_encryption: 'Security',
  tracking_technologies_disclosure: 'Tracking',
}

const RISK_COLORS_MAP = { Low: '#00966C', Medium: '#A39382', High: '#D14124' }

export default function Analyze() {
  const [policyText, setPolicyText] = useState('')
  const [policyUrl, setPolicyUrl] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [result, setResult] = useState(null)

  const handleSubmit = async (e) => {
    e.preventDefault()
    setError(null)
    setResult(null)
    setLoading(true)

    try {
      const body = {}
      if (policyText.trim()) body.policy_text = policyText.trim()
      if (policyUrl.trim()) body.policy_url = policyUrl.trim()

      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })

      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        throw new Error(data.detail || `Request failed (${res.status})`)
      }

      setResult(await res.json())
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const canSubmit = (policyText.trim().length > 0 || policyUrl.trim().length > 0) && !loading

  const radarData = result
    ? Object.keys(RADAR_SHORT).map((k) => ({
        indicator: RADAR_SHORT[k],
        value: result[k] ? 100 : 0,
      }))
    : []

  const scoreBg =
    result &&
    (result.risk_level === 'Low'
      ? 'border-l-byu-green'
      : result.risk_level === 'Medium'
        ? 'border-l-byu-gold'
        : 'border-l-byu-orange')

  const exportReport = () => {
    if (!result) return
    const indicators = Object.entries(INDICATOR_LABELS)
      .map(([k, label]) => `<tr><td style="padding:6px 12px;border-bottom:1px solid #eee">${label}</td><td style="padding:6px 12px;border-bottom:1px solid #eee;text-align:center;color:${result[k] ? '#00966C' : '#D14124'};font-weight:600">${result[k] ? 'PASS' : 'FAIL'}</td></tr>`)
      .join('')
    const coppa = result.coppa_analysis || {}
    const gdpr = result.gdpr_analysis || {}
    const thirdParties = (result.third_party_details || [])
      .map((tp) => `<tr><td style="padding:4px 12px;border-bottom:1px solid #eee">${tp.name}</td><td style="padding:4px 12px;border-bottom:1px solid #eee">${tp.purpose}</td><td style="padding:4px 12px;border-bottom:1px solid #eee">${(tp.data_shared || []).join(', ')}</td></tr>`)
      .join('')
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Privacy Policy Compliance Report</title><style>body{font-family:Inter,system-ui,sans-serif;max-width:800px;margin:0 auto;padding:40px 20px;color:#1a1a2e}h1{color:#002E5D;font-size:24px;margin-bottom:4px}h2{color:#002E5D;font-size:16px;margin-top:32px;border-bottom:2px solid #002E5D;padding-bottom:6px}table{width:100%;border-collapse:collapse;margin:12px 0;font-size:14px}.score-box{display:inline-block;padding:12px 24px;border-radius:8px;text-align:center;margin-right:12px}.meta{color:#7C878E;font-size:13px}@media print{body{padding:20px}}</style></head><body><h1>Privacy Policy Compliance Report</h1><p class="meta">Generated by BYU EdTech Privacy Lab &middot; ${new Date().toLocaleDateString()}</p><div style="margin:24px 0"><div class="score-box" style="background:#f0f4f8;border:2px solid ${result.risk_level === 'Low' ? '#00966C' : result.risk_level === 'Medium' ? '#A39382' : '#D14124'}"><div style="font-size:28px;font-weight:700;color:#002E5D">${result.compliance_score}/9</div><div style="font-size:12px;color:#7C878E">Compliance Score</div></div><div class="score-box" style="background:${result.risk_level === 'Low' ? '#f0fdf4' : result.risk_level === 'Medium' ? '#fffbeb' : '#fef2f2'};border:2px solid ${RISK_COLORS_MAP[result.risk_level]}"><div style="font-size:28px;font-weight:700;color:${RISK_COLORS_MAP[result.risk_level]}">${result.risk_level}</div><div style="font-size:12px;color:#7C878E">Risk Level</div></div></div><h2>Privacy Indicators</h2><table>${indicators}</table><h2>Regulatory Compliance</h2><table><tr><td style="padding:6px 12px;border-bottom:1px solid #eee"><strong>COPPA</strong></td><td style="padding:6px 12px;border-bottom:1px solid #eee">Mentions: ${coppa.mentions_coppa ? 'Yes' : 'No'} | Claims Compliance: ${coppa.claims_compliance ? 'Yes' : 'No'}${coppa.age_threshold_stated ? ' | Age Threshold: ' + coppa.age_threshold_stated : ''}</td></tr><tr><td style="padding:6px 12px;border-bottom:1px solid #eee"><strong>GDPR</strong></td><td style="padding:6px 12px;border-bottom:1px solid #eee">Mentions: ${gdpr.mentions_gdpr ? 'Yes' : 'No'} | Claims Compliance: ${gdpr.claims_compliance ? 'Yes' : 'No'}${gdpr.age_threshold_stated ? ' | Age Threshold: ' + gdpr.age_threshold_stated : ''}</td></tr></table>${thirdParties ? `<h2>Third-Party Data Sharing (${result.third_party_details.length} entities)</h2><table><tr style="background:#f8f9fa"><th style="padding:6px 12px;text-align:left;font-size:12px;text-transform:uppercase;color:#7C878E">Entity</th><th style="padding:6px 12px;text-align:left;font-size:12px;text-transform:uppercase;color:#7C878E">Purpose</th><th style="padding:6px 12px;text-align:left;font-size:12px;text-transform:uppercase;color:#7C878E">Data Shared</th></tr>${thirdParties}</table>` : ''}<div style="margin-top:40px;padding-top:16px;border-top:1px solid #eee;font-size:11px;color:#7C878E;text-align:center">BYU EdTech Privacy Lab &middot; Department of Information Systems &middot; Marriott School of Business &middot; Brigham Young University</div></body></html>`
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'privacy-compliance-report.html'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <main className="pt-14">
      {/* Header */}
      <div className="bg-navy text-white">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <p className="text-xs font-semibold uppercase tracking-[0.15em] text-byu-lightblue mb-2">
            Interactive Tool
          </p>
          <h1
            className="text-3xl sm:text-4xl font-bold mb-3"
            style={{ fontFamily: "'Merriweather', serif" }}
          >
            Analyze a Privacy Policy
          </h1>
          <p className="text-white/70 max-w-2xl leading-relaxed">
            Paste any K-12 edtech privacy policy below and get an instant compliance assessment
            powered by our AI analysis framework.
          </p>
        </div>
      </div>

      {/* Form */}
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        <form onSubmit={handleSubmit} className="bg-surface border border-border rounded-lg p-6">
          <label className="block text-sm font-medium text-text-primary mb-1.5">
            Privacy Policy Text
          </label>
          <textarea
            className="w-full h-48 border border-border rounded-lg p-3 text-sm bg-page text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-royal/40 resize-y"
            placeholder="Paste the full privacy policy text here..."
            value={policyText}
            onChange={(e) => setPolicyText(e.target.value)}
          />

          <div className="mt-4">
            <label className="block text-sm font-medium text-text-primary mb-1.5">
              <span className="flex items-center gap-1.5">
                <LinkIcon className="w-3.5 h-3.5" /> Policy URL
                <span className="text-text-muted font-normal">(optional)</span>
              </span>
            </label>
            <input
              type="url"
              className="w-full border border-border rounded-lg px-3 py-2 text-sm bg-page text-text-primary placeholder:text-text-muted focus:outline-none focus:ring-2 focus:ring-royal/40"
              placeholder="https://example.com/privacy-policy"
              value={policyUrl}
              onChange={(e) => setPolicyUrl(e.target.value)}
            />
          </div>

          <p className="text-xs text-text-muted mt-2">
            For best results, paste the full policy text. URL fetching may miss dynamically loaded content.
          </p>

          <button
            type="submit"
            disabled={!canSubmit}
            className="mt-4 inline-flex items-center gap-2 bg-royal text-white px-5 py-2.5 rounded-lg text-sm font-medium hover:bg-navy transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" /> Analyzing...
              </>
            ) : (
              <>
                <Shield className="w-4 h-4" /> Analyze
              </>
            )}
          </button>
        </form>

        {error && (
          <div className="mt-4 bg-red-50 border border-red-200 rounded-lg p-4 flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
            <p className="text-sm text-red-700">{error}</p>
          </div>
        )}
      </section>

      {/* Results */}
      {result && (
        <>
          {/* Export bar */}
          <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-4">
            <div className="flex justify-end">
              <button
                onClick={exportReport}
                className="inline-flex items-center gap-2 bg-navy text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-navy-light transition-colors"
              >
                <Download className="w-4 h-4" />
                Download Report
              </button>
            </div>
          </section>

          {/* Score summary cards */}
          <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-10">
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
              <div className={`bg-surface border border-border border-l-4 ${scoreBg} rounded-lg p-4`}>
                <p className="text-xl font-bold text-navy">{result.compliance_score}/9</p>
                <p className="text-sm font-medium text-text-primary mt-0.5">Compliance Score</p>
              </div>
              <div className={`bg-surface border border-border border-l-4 ${scoreBg} rounded-lg p-4`}>
                <p className="text-xl font-bold text-navy">{result.risk_level}</p>
                <p className="text-sm font-medium text-text-primary mt-0.5">Risk Level</p>
              </div>
              <div className="bg-surface border border-border border-l-4 border-l-royal rounded-lg p-4">
                <p className="text-xl font-bold text-navy">
                  {result.coppa_analysis?.claims_compliance ? 'Yes' : 'No'}
                </p>
                <p className="text-sm font-medium text-text-primary mt-0.5">COPPA Compliant</p>
              </div>
              <div className="bg-surface border border-border border-l-4 border-l-royal rounded-lg p-4">
                <p className="text-xl font-bold text-navy">
                  {result.gdpr_analysis?.claims_compliance ? 'Yes' : 'No'}
                </p>
                <p className="text-sm font-medium text-text-primary mt-0.5">GDPR Compliant</p>
              </div>
            </div>
          </section>

          {/* Indicators table + radar */}
          <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-10">
            <div className="grid lg:grid-cols-2 gap-5">
              {/* Table */}
              <div className="bg-surface border border-border rounded-lg overflow-hidden">
                <div className="p-6 pb-3">
                  <h3 className="text-lg font-semibold text-text-primary mb-0.5">
                    9 Privacy Indicators
                  </h3>
                  <p className="text-sm text-text-muted">
                    Individual compliance check for each indicator
                  </p>
                </div>
                <table className="w-full text-sm">
                  <tbody className="divide-y divide-border">
                    {Object.entries(INDICATOR_LABELS).map(([key, label]) => (
                      <tr key={key} className="hover:bg-page/50 transition-colors">
                        <td className="px-6 py-2.5 text-text-primary">{label}</td>
                        <td className="px-6 py-2.5 text-right">
                          {result[key] ? (
                            <CheckCircle className="w-5 h-5 text-emerald-600 inline" />
                          ) : (
                            <XCircle className="w-5 h-5 text-red-500 inline" />
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Radar */}
              <div className="bg-surface border border-border rounded-lg p-6">
                <h3 className="text-lg font-semibold text-text-primary mb-1">Compliance Radar</h3>
                <p className="text-sm text-text-muted mb-4">
                  Visual overview of policy coverage
                </p>
                <div className="h-[340px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <RadarChart data={radarData} outerRadius="70%">
                      <PolarGrid stroke="#E5E7EB" />
                      <PolarAngleAxis dataKey="indicator" tick={{ fill: '#7C878E', fontSize: 11 }} />
                      <PolarRadiusAxis angle={90} domain={[0, 100]} tick={{ fill: '#C7C9C7', fontSize: 10 }} />
                      <Radar
                        dataKey="value"
                        stroke="#002E5D"
                        fill="#002E5D"
                        fillOpacity={0.15}
                        strokeWidth={2}
                      />
                    </RadarChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </div>
          </section>

          {/* Third-party details */}
          {result.third_party_details && result.third_party_details.length > 0 && (
            <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-10">
              <div className="bg-surface border border-border rounded-lg p-6">
                <h3 className="text-lg font-semibold text-text-primary mb-1">
                  Third-Party Data Sharing
                </h3>
                <p className="text-sm text-text-muted mb-4">
                  Entities receiving user data and what is shared
                </p>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border bg-page">
                        <th className="text-left font-semibold text-text-muted text-xs uppercase tracking-wider px-4 py-2.5">
                          Entity
                        </th>
                        <th className="text-left font-semibold text-text-muted text-xs uppercase tracking-wider px-4 py-2.5">
                          Purpose
                        </th>
                        <th className="text-left font-semibold text-text-muted text-xs uppercase tracking-wider px-4 py-2.5">
                          Data Shared
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {result.third_party_details.map((tp, i) => (
                        <tr key={i} className="hover:bg-page/50 transition-colors">
                          <td className="px-4 py-2.5 font-medium text-text-primary">{tp.name}</td>
                          <td className="px-4 py-2.5 text-text-secondary">{tp.purpose}</td>
                          <td className="px-4 py-2.5 text-text-muted">
                            {tp.data_shared?.join(', ') || 'Not specified'}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </section>
          )}

          {/* COPPA + GDPR analysis */}
          <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
            <div className="grid lg:grid-cols-2 gap-5">
              {/* COPPA */}
              <div className="bg-surface border border-border rounded-lg p-6">
                <div className="flex items-center gap-2 mb-4">
                  <FileText className="w-5 h-5 text-navy" />
                  <h3 className="text-lg font-semibold text-text-primary">COPPA Analysis</h3>
                </div>
                {result.coppa_analysis && (
                  <div className="space-y-3 text-sm">
                    <div className="flex justify-between">
                      <span className="text-text-muted">Mentions COPPA</span>
                      <span className="font-medium text-text-primary">
                        {result.coppa_analysis.mentions_coppa ? 'Yes' : 'No'}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-text-muted">Claims Compliance</span>
                      <span className="font-medium text-text-primary">
                        {result.coppa_analysis.claims_compliance ? 'Yes' : 'No'}
                      </span>
                    </div>
                    {result.coppa_analysis.consent_methods?.length > 0 && (
                      <div>
                        <span className="text-text-muted">Consent Methods</span>
                        <div className="flex flex-wrap gap-1.5 mt-1">
                          {result.coppa_analysis.consent_methods.map((m, i) => (
                            <span
                              key={i}
                              className="inline-block bg-page border border-border rounded px-2 py-0.5 text-xs text-text-secondary"
                            >
                              {m.replace(/_/g, ' ')}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                    {result.coppa_analysis.exceptions_claimed?.length > 0 && (
                      <div>
                        <span className="text-text-muted">Exceptions Claimed</span>
                        <div className="flex flex-wrap gap-1.5 mt-1">
                          {result.coppa_analysis.exceptions_claimed.map((e, i) => (
                            <span
                              key={i}
                              className="inline-block bg-page border border-border rounded px-2 py-0.5 text-xs text-text-secondary"
                            >
                              {e.replace(/_/g, ' ')}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                    {result.coppa_analysis.age_threshold_stated && (
                      <div className="flex justify-between">
                        <span className="text-text-muted">Age Threshold</span>
                        <span className="font-medium text-text-primary">
                          {result.coppa_analysis.age_threshold_stated}
                        </span>
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* GDPR */}
              <div className="bg-surface border border-border rounded-lg p-6">
                <div className="flex items-center gap-2 mb-4">
                  <FileText className="w-5 h-5 text-navy" />
                  <h3 className="text-lg font-semibold text-text-primary">GDPR Analysis</h3>
                </div>
                {result.gdpr_analysis && (
                  <div className="space-y-3 text-sm">
                    <div className="flex justify-between">
                      <span className="text-text-muted">Mentions GDPR</span>
                      <span className="font-medium text-text-primary">
                        {result.gdpr_analysis.mentions_gdpr ? 'Yes' : 'No'}
                      </span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-text-muted">Claims Compliance</span>
                      <span className="font-medium text-text-primary">
                        {result.gdpr_analysis.claims_compliance ? 'Yes' : 'No'}
                      </span>
                    </div>
                    {result.gdpr_analysis.consent_methods?.length > 0 && (
                      <div>
                        <span className="text-text-muted">Consent Methods</span>
                        <div className="flex flex-wrap gap-1.5 mt-1">
                          {result.gdpr_analysis.consent_methods.map((m, i) => (
                            <span
                              key={i}
                              className="inline-block bg-page border border-border rounded px-2 py-0.5 text-xs text-text-secondary"
                            >
                              {m.replace(/_/g, ' ')}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                    {result.gdpr_analysis.lawful_bases?.length > 0 && (
                      <div>
                        <span className="text-text-muted">Lawful Bases</span>
                        <div className="flex flex-wrap gap-1.5 mt-1">
                          {result.gdpr_analysis.lawful_bases.map((b, i) => (
                            <span
                              key={i}
                              className="inline-block bg-page border border-border rounded px-2 py-0.5 text-xs text-text-secondary"
                            >
                              {b.replace(/_/g, ' ')}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                    {result.gdpr_analysis.age_threshold_stated && (
                      <div className="flex justify-between">
                        <span className="text-text-muted">Age Threshold</span>
                        <span className="font-medium text-text-primary">
                          {result.gdpr_analysis.age_threshold_stated}
                        </span>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </div>
          </section>
        </>
      )}
    </main>
  )
}
